criar pagina de login - BEM-24
G2BC/BEM-web pull request #18
Opened 2024-10-17 00:36 UTC by Devild-dev

Criar página de login BEM-24

2024-10-17 16:38 UTC, wilyJ80 commented
funcionou ok :ok_hand: . esse commit é só pra página de registrar, correto? @Devild-dev só me tire essa dúvida pra eu aceitar aqui

2024-10-18 01:36 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +import background from '../../../assets/background.png'; // Importe a imagem de fundo
Remover comentátrios
```suggestion
import background from '../../../assets/background.png'; 
```

2024-10-18 01:39 UTC, Adeonita requested changes

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +import logo from '../../../assets/logoicon.png'; // Importe a imagem do logo
Remover comentários


```suggestion
import logo from '../../../assets/logoicon.png'; 
```

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +// import ReCAPTCHA from 'react-google-recaptcha';
Remover comentários


```suggestion

```

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +  minHeight: '100vh', // Ajustado para usar minHeight em vez de height
Remover comentários

```suggestion
  minHeight: '100vh', 
```

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +    padding: theme.spacing(4), // Reduzir padding em telas menores
Remover comentários

```suggestion
    padding: theme.spacing(4), 
```

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +    display: 'none', // Ocultar o texto de boas-vindas em telas menores
Remover comentários


```suggestion
    display: 'none', 
```

2024-10-18 01:39 UTC, Adeonita commented on src/components/Pages/LoginPage/LoginPage.tsx
> +  textAlign: 'left', // Justificar o texto
Remover comentários


```suggestion
  textAlign: 'left', 
```

2024-10-18 01:41 UTC, Adeonita reviewed
Atentar-se para colocar o número da task jira no **nome da branch** não no título e linkar a task na descrição do pr

2024-10-22 00:05 UTC, Devild-dev reviewed
Comentários retirados do código.

2024-10-22 00:30 UTC, wilyJ80 approved these changes

2024-10-22 13:01 UTC, merged